CC = clang
ARGS = -Wall

all:
	$(CC) $(ARGS) ./list/listmegazorde.c -o listexe
	$(CC) $(ARGS) ./stack/stack.c -o stackexe
debug:
	$(CC) $(ARGS) -g ./list/listmegazorde.c -o listexe
	$(CC) $(ARGS) -g ./stack/stack.c -o stackexe
