CC=g++
CCFLAGS= -Wall

cast_problem_example:
	$(CC) $(CCFLAGS) -o cast_problem_example.o cast_problem_example.cpp

defines:
	$(CC) $(CCFLAGS) -o defines.o defines.cpp

field_static:
	$(CC) $(CCFLAGS) -o field_static.o field_static.cpp

read_file:
	$(CC) $(CCFLAGS) -o read_file.o read_file.cpp

void_pointer_fun:
	$(CC) $(CCFLAGS) -o void_pointer_fun.o void_pointer_fun.cpp

clean:
	rm *.o	
