CC=gcc
CFLAGS=-Wall -g

exec1:
	$(CC) $(CFLAGS) exec1.c -o ex1

exec3:
	$(CC) $(CFLAGS) exec3.c -o ex3

exec4:
	$(CC) $(CFLAGS) exec4.c -o ex4

exec6:
	$(CC) $(CFLAGS) exec6.c -o ex6

exec7:
	$(CC) $(CFLAGS) exec7.c -o ex7

exec8:
	$(CC) $(CFLAGS) exec8.c -o ex8

clean:
	rm -f ex1 ex3 ex4 ex6 ex7 ex8
