#!/bin/bash

if (($# < 2 ))
then
	echo Usage: finder '['parttern ']' '['path']'
	exit 0
fi

for file in $(find $2 -type f)
do
	echo Searching on $file
	if grep $1 < $file
	then
		echo $file >> files.txt
	fi
done




